### ISSUE TITLE
Газрын зургийг дүүргэлттэй болгох

### ISSUE THREAD

**Issue by byambatsogt** [byambatsogt/geoWMS#2]
![](https://user-images.githubusercontent.com/1480970/83994620-8bd7a280-a989-11ea-8fc1-9da7c2aaa4ca.png)

**Comment by ariunbayar** [comment]
ref 14786de07c6c026e1dbc10e40718671ed797a24b
ref 28c6955bfd9e1158f1a22cbc6286cf418a448afc
